services:
  - type: web
    name: kydb-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false